steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    entrypoint: bash
    args:
      - "-c"
      - |
        pip3 install -r requirements.txt
        python3 manage.py collectstatic --noinput
        gcloud app deploy app.yaml --quiet
timeout: "1200s"
